### ISSUE TITLE
Doesn't seem to work for Alfred 3

### ISSUE THREAD

**Issue by RaviH** [mibexsoftware/alfred-stash-workflow#2]
Hello,

Thank you for this excellent workflow. I am using this with Alfred 3 and the first time I started it, it asked for the location of Alfred 2. I tried giving it Alfred 3 location but it has stopped working since.

I cannot get to the point where I can make it ask the question about the location of Alfred 2 again. I have deleted it and cleared the cache and deleted whatever local files I could find. 

Can you please help? 

Thank you!
Ravi

**Comment by drfisher** [comment]
+1

**Comment by mrueegg** [comment]
Hi,

Thanks for your feedback. You're right, the plug-in doesn't properly work with Alfred 3. I'll fix this and publish a new version of the plug-in in the next few days.

**Comment by mrueegg** [comment]
Fixed with release 1.2.0. Thanks for raising this issue!

**Comment by RaviH** [comment]
+1 Seems to be working i.e. is fetching repos still but it got the projects, so it should be able to get the repos as well! 

Thank you for your support. This is excellent work!
